//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabTestLaptops
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laptop
    {
        public int ID { get; set; }
        public string Make { get; set; }
        public int DollarValue { get; set; }
        public int QuantityAvailable { get; set; }
        public int BrandID { get; set; }
    
        public virtual Brand Brand { get; set; }
    }
}
